name: Deploy on AWS

on:
  push:
    branches:
      - main
jobs:
   deploy:
     runs-on: ubuntu-latest

     steps:
     - name: clone the code 
       uses: actions/checkout@v4
     
     - name: checking on a machine
       run: |
          echo "hello"
          ls
          pwd
       
